# Generated by Django 5.1.5 on 2025-02-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_dealerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_dealership',
            },
        ),
        migrations.CreateModel(
            name='DealershipUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Sales', 'Sales'), ('Mechanic', 'Mechanic')], max_length=20)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_users', to='car_dealership.cardealership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_dealership_user',
                'unique_together': {('user', 'dealership', 'role')},
            },
        ),
    ]
