# Generated by Django 5.1.5 on 2025-02-01 19:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0001_initial'),
        ('cars', '0002_rename_car_dealership_carmodel_dealership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDealership',
            new_name='DealershipModel',
        ),
        migrations.RenameModel(
            old_name='DealershipUser',
            new_name='DealershipUserModel',
        ),
        migrations.AlterModelTable(
            name='dealershipmodel',
            table='dealerships',
        ),
        migrations.AlterModelTable(
            name='dealershipusermodel',
            table='dealership_users',
        ),
    ]
