# Generated by Django 5.1.5 on 2025-02-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_dealership',
            new_name='dealership',
        ),
    ]
