# Generated by Django 5.1.5 on 2025-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carcurrencypricemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='edit_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('NeedReview', 'Needreview')], default='Active', max_length=15),
        ),
    ]
