# Generated by Django 5.1.5 on 2025-01-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('DealerAdmin', 'Dealer Admin'), ('DealerManager', 'Dealer Manager')], default='Buyer', max_length=15),
        ),
    ]
