# Generated by Django 5.1.5 on 2025-02-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
    ]
