# Generated by Django 5.1.5 on 2025-02-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateISOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currencyCodeA', models.IntegerField()),
                ('currencyCodeB', models.IntegerField()),
                ('rateBuy', models.DecimalField(decimal_places=5, max_digits=15)),
                ('rateSell', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'db_table': 'exchange_rate_iso',
                'ordering': ['id'],
            },
        ),
    ]
